name: Coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install kcov
      run: |
        sudo apt-get -y install binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev
        wget https://github.com/SimonKagstrom/kcov/releases/download/pre-v40/kcov-amd64.tar.gz
        mkdir kcov
        tar -C kcov -xzf kcov-amd64.tar.gz
        rm kcov-amd64.tar.gz
        echo "PATH=$(pwd)/kcov/usr/local/bin:$PATH" >> $GITHUB_ENV
    - name: Build and run tests
      run: |
        RUSTFLAGS="-C link-dead-code" cargo test --no-run
        mkdir -p target/cov
        exe="$(find target/debug/deps -type f -executable)"
        kcov --exclude-pattern=$CARGO_HOME --verify "target/cov/$(basename $exe)" $exe
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./target/cov
        flags: unittests
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
