name: Coverage
on:
  push:
    branches: [master]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Add llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        RUSTFLAGS: "-Zinstrument-coverage"
        LLVM_PROFILE_FILE: "target/cov/coverage-%p-%m.profraw"
    - name: Run grcov
      run: |
        wget "https://github.com/mozilla/grcov/releases/download/v0.8.0/grcov-linux-x86_64.tar.bz2"
        tar xf grcov-linux-x86_64.tar.bz2
        rm grcov-linux-x86_64.tar.bz2
        ./grcov . -s . --binary-path ./target/debug -t lcov --branch --ignore-not-existing -o coverage.lcov
    - name: Upload coveracoverage.lcov
        flags: unittests
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
