name: Coverage
on:
  push:
    branches: [master]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Add llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        RUSTFLAGS: "-Zinstrument-coverage"
    - name: Collect test
      uses: actions-rs/grcov@v0.1
      id: coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ${{ steps.coverage.outputs.report }}
        flags: unittests
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
